# fly.toml app configuration file generated for home-project2 on 2023-11-16T23:55:50+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "home-project2"
primary_region = "ams"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
